reference integrity of shared module integ tests
Sage-Bionetworks/BridgeIntegrationTests pull request #151
Opened 2017-04-17 21:40 UTC by zaclinsage

tests done;
see also:

2017-04-18 00:26 UTC, DwayneJengSage requested changes
We also need tests for:
* Creating a module that points to a non-existent schema.
* Creating a module that points to a non-existent survey.
* Updating a module that points to a non-existent schema.
* Updating a module that points to a non-existent survey.
* Logical and permanent deletes of a survey when it's in use by a module.

2017-04-18 00:26 UTC, DwayneJengSage commented on src/test/java/org/sagebionetworks/bridge/sdk/integration/SharedModuleMetadataTest.java
> +        UploadSchema uploadSchema = makeSimpleSchema(SCHEMA_ID, (long) 0, 0L);
To make sure tests don't interfere with each other, it's probably better to randomly generate a Schema ID.

2017-04-18 00:26 UTC, DwayneJengSage commented on src/test/java/org/sagebionetworks/bridge/sdk/integration/SharedModuleMetadataTest.java
> +        UploadSchema retSchema = devUploadSchemasApi.createUploadSchema(uploadSchema).execute().body();
Minor: We don't actually need the return value here.

2017-04-18 00:26 UTC, DwayneJengSage commented on src/test/java/org/sagebionetworks/bridge/sdk/integration/SharedModuleMetadataTest.java
> +        GuidCreatedOnVersionHolder retSurvey = devSurveysApi.createSurvey(survey).execute().body();
createSurvey() generates its own guid and createdOn. You don't need to provide one in the input.

2017-04-18 00:26 UTC, DwayneJengSage commented on src/test/java/org/sagebionetworks/bridge/sdk/integration/SharedModuleMetadataTest.java
> +
Why do we need to create a schema here? We already create one in before().

2017-04-18 00:26 UTC, DwayneJengSage commented on src/test/java/org/sagebionetworks/bridge/sdk/integration/SurveyTest.java
> +        String moduleId = "integ-test-module-delete";
We should generate a random module ID so we don't have conflicts between test runs.

2017-04-18 00:26 UTC, DwayneJengSage commented on src/test/java/org/sagebionetworks/bridge/sdk/integration/UploadSchemaTest.java
> +        String moduleId = "integ-test-module-delete";
Similarly, we want a random module ID here also.

2017-04-18 00:26 UTC, DwayneJengSage commented on src/test/java/org/sagebionetworks/bridge/sdk/integration/UploadSchemaTest.java
> +        UploadSchema uploadSchema = makeSimpleSchema("dummy-schema-id", (long) 0, 0L);
Similarly, we want a random schema ID.

2017-04-18 00:26 UTC, DwayneJengSage commented on src/test/java/org/sagebionetworks/bridge/sdk/integration/UploadSchemaTest.java
> +        SharedModuleMetadata metadataToCreate = new SharedModuleMetadata().id(moduleId).version(retSchema.getVersion().intValue())
Schema version and module version are unrelated. Don't try to match them.

2017-04-18 22:44 UTC, DwayneJengSage requested changes

2017-04-18 22:44 UTC, DwayneJengSage commented on src/test/java/org/sagebionetworks/bridge/sdk/integration/SharedModuleMetadataTest.java
> +        sharedDeveloperModulesApi.updateMetadata(moduleId, METADATA_VERSION.intValue(), metadataToUpdate).execute();
I think this test (and testUpdateWithoutSurvey()) would actually throw a 404, not a 400, since the module doesn't exist. You need to create the module first, then update it to a non-existent survey or schema.

2017-04-18 22:44 UTC, DwayneJengSage commented on src/test/java/org/sagebionetworks/bridge/sdk/integration/SurveyTest.java
> +            sharedSurveysApi.deleteSurvey(retSurvey.getGuid(), retSurvey.getCreatedOn(), true).execute();
This test is identical to the previous test. Both try to delete the survey permanently.

2017-04-18 22:44 UTC, DwayneJengSage commented on src/test/java/org/sagebionetworks/bridge/sdk/integration/SurveyTest.java
> +            sharedSurveysApi.deleteSurvey(retSurvey.getGuid(), retSurvey.getCreatedOn(), false).execute();
In your cleanup code, you need to delete the survey permanently. Otherwise, logically deleted surveys will pile up in the test DB.

Also, you need to be an admin to delete surveys permanently.

2017-04-18 22:44 UTC, DwayneJengSage commented on src/test/java/org/sagebionetworks/bridge/sdk/integration/SurveyTest.java
> +            sharedSurveysApi.deleteSurvey(retSurvey.getGuid(), retSurvey.getCreatedOn(), true).execute();
You need to be an admin to delete a survey permanently.

2017-04-18 22:44 UTC, DwayneJengSage commented on src/test/java/org/sagebionetworks/bridge/sdk/integration/SharedModuleMetadataTest.java
> +    private String schemaId = "dummy-schema";
Minor: You don't need to init the schemaId with a value, since we just overwrite it immediately anyway.

2017-04-18 22:44 UTC, DwayneJengSage commented on src/test/java/org/sagebionetworks/bridge/sdk/integration/SharedModuleMetadataTest.java
> +        UploadSchema uploadSchema = makeSimpleSchema(schemaId, METADATA_REV, METADATA_VERSION);
METADATA_REV and METADATA_VERSION aren't accurate. You're creating a schema, not a module.

2017-04-18 22:44 UTC, DwayneJengSage commented on src/test/java/org/sagebionetworks/bridge/sdk/integration/UploadSchemaTest.java
> +            sharedUploadSchemasApi.deleteAllRevisionsOfUploadSchema(studyIdShared, retSchema.getSchemaId()).execute();
You need to be an admin to delete schemas.

2017-04-18 22:44 UTC, DwayneJengSage commented on src/test/java/org/sagebionetworks/bridge/sdk/integration/SharedModuleMetadataTest.java
> +        devSurveysApi.deleteSurvey(surveyGuid, surveyCreatedOn, true).execute();
You need to be admin to delete schemas and surveys.

2017-04-18 22:58 UTC, zaclinsage commented on src/test/java/org/sagebionetworks/bridge/sdk/integration/SharedModuleMetadataTest.java
> +        sharedDeveloperModulesApi.updateMetadata(moduleId, METADATA_VERSION.intValue(), metadataToUpdate).execute();
yeah i thought i created in @before but actually not.

2017-04-19 00:31 UTC, DwayneJengSage requested changes

2017-04-19 00:31 UTC, DwayneJengSage commented on src/test/java/org/sagebionetworks/bridge/sdk/integration/SharedModuleMetadataTest.java
> +        sharedDeveloperModulesApi.updateMetadata(moduleId, SCHEMA_VERSION.intValue(), metadataToUpdate).execute();
You're trying to use the schema version instead of the module version.

You also still haven't created the module, so this will still throw a 404 instead of a 400.

(Here and in testUpdateWithoutSurvey().)

2017-04-19 00:31 UTC, DwayneJengSage commented on src/test/java/org/sagebionetworks/bridge/sdk/integration/SharedModuleMetadataTest.java
> +                .body();
You don't need to create a valid module before you create an invalid one. (Here and in testCreateWithoutSurvey().)

2017-04-19 21:28 UTC, DwayneJengSage requested changes

2017-04-19 22:51 UTC, merged