Adding a test for a sequence schedule (time-limited recurring schedule).
Sage-Bionetworks/BridgeIntegrationTests pull request #193
Opened 2017-09-14 21:33 UTC by alxdarksage

2017-09-16 00:07 UTC, DwayneJengSage requested changes

2017-09-16 00:07 UTC, DwayneJengSage commented on src/test/java/org/sagebionetworks/bridge/sdk/integration/ScheduleTest.java
> +        assertEquals(3, list.getItems().size());
This test will fail if there are other schedules in the API study. (Which is very likely to happen if a previous test fails to clean up, or if there's another schedule from a manual test.) You should instead generate a random label for your activity, then filter the ScheduledActivityList for activities that match your label. See other tests in ScheduleTest or ScheduledActivityTest for examples.

2017-09-18 18:37 UTC, alxdarksage commented
Updated based on review.

2017-09-18 20:41 UTC, DwayneJengSage approved these changes

2017-09-18 22:57 UTC, DwayneJengSage requested changes

2017-09-18 22:57 UTC, DwayneJengSage commented on src/test/java/org/sagebionetworks/bridge/sdk/integration/AppConfigTest.java
> +public class AppConfigTest {
Should this have been split off into a different code review? It looks like we're bundling two different changelists when we don't need to be.

2017-09-18 22:57 UTC, DwayneJengSage commented on src/test/java/org/sagebionetworks/bridge/sdk/integration/ScheduleTest.java
> +        //schedule.setSequencePeriod("P3D");
It looks like this test still works even without a sequence period, which suggests to me that it's not testing sequence period at all. Should we tweak the test to make sure that it's testing what we think it's testing?

2017-09-18 23:00 UTC, alxdarksage commented on src/test/java/org/sagebionetworks/bridge/sdk/integration/AppConfigTest.java
> +public class AppConfigTest {
Yes, sorry. This should be here.

2017-09-18 23:03 UTC, DwayneJengSage requested changes

2017-09-18 23:03 UTC, DwayneJengSage commented on src/test/java/org/sagebionetworks/bridge/sdk/integration/AppConfigTest.java
> +    }
Do we need to delete the users we've created?

2017-09-18 23:03 UTC, DwayneJengSage commented on src/test/java/org/sagebionetworks/bridge/sdk/integration/AppConfigTest.java
> +        assertEquals(surveyRef1, appConfig.getSurveyReferences().get(0));
You're comparing the object you created with itself, not with the result from the server.

2017-09-18 23:14 UTC, DwayneJengSage approved these changes

2017-09-19 16:48 UTC, merged