Test of signing up and signing in with external ID.
Sage-Bionetworks/BridgeIntegrationTests pull request #259
Opened 2018-04-16 21:42 UTC by alxdarksage

2018-04-18 21:54 UTC, DwayneJengSage requested changes

2018-04-18 21:54 UTC, DwayneJengSage commented on src/test/java/org/sagebionetworks/bridge/sdk/integration/ExternalIdSignUpTest.java
> +        }
This conflicts with local testing. It would be better to create a randomized external ID instead.

2018-04-18 21:54 UTC, DwayneJengSage commented on src/test/java/org/sagebionetworks/bridge/sdk/integration/ExternalIdSignUpTest.java
> +            authClient.signInV4(signIn).execute().body();
Need to add a fail().

2018-04-19 17:16 UTC, alxdarksage commented on src/test/java/org/sagebionetworks/bridge/sdk/integration/ExternalIdSignUpTest.java
> +        }
Changed this to create and delete to random external IDs.

2018-04-19 17:16 UTC, alxdarksage commented on src/test/java/org/sagebionetworks/bridge/sdk/integration/ExternalIdSignUpTest.java
> +            authClient.signInV4(signIn).execute().body();
Added.

2018-04-19 17:17 UTC, alxdarksage commented
Also fixed a permission issue with the clients that became apparent once the tests were changed.

2018-04-19 20:50 UTC, DwayneJengSage requested changes

2018-04-19 20:50 UTC, DwayneJengSage commented on src/test/java/org/sagebionetworks/bridge/sdk/integration/ExternalIdSignUpTest.java
> +            ExternalIdentifierList list = devIdsClient.getExternalIds(null, 50, null, null).execute().body();
Consider using idFilter, so we don't have to page through 50 different external IDs to find the one we created.

2018-04-19 20:50 UTC, DwayneJengSage commented on src/test/java/org/sagebionetworks/bridge/sdk/integration/ExternalIdSignUpTest.java
> +                }
Break statement, so we don't have to keep looping over external IDs after we've found the one we're looking for.

Also, if we don't find the external ID, the test doesn't fail.

2018-04-20 16:55 UTC, alxdarksage commented on src/test/java/org/sagebionetworks/bridge/sdk/integration/ExternalIdSignUpTest.java
> +            ExternalIdentifierList list = devIdsClient.getExternalIds(null, 50, null, null).execute().body();
Updated, also removes the loop below

2018-04-20 16:55 UTC, alxdarksage commented on src/test/java/org/sagebionetworks/bridge/sdk/integration/ExternalIdSignUpTest.java
> +                }
loop removed

2018-04-20 22:13 UTC, DwayneJengSage approved these changes

2018-04-20 23:15 UTC, merged