Tests of new search API.
Sage-Bionetworks/BridgeIntegrationTests pull request #267
Opened 2018-05-21 19:16 UTC by alxdarksage

Many of these changes are from the library update, where booleans go from a getFoo accessor to an isFoo() accessor. And one new test class for the search API.

2018-05-22 23:48 UTC, DwayneJengSage requested changes

2018-05-22 23:48 UTC, DwayneJengSage commented on src/test/java/org/sagebionetworks/bridge/sdk/integration/AccountSummarySearchTest.java
> +        }
We create a researcher in several tests, but we only delete one researcher. I think we should create the researcher and worker in the BeforeClass instead. This way, we only need to create them once, and we are more likely to be able to clean them up afterward.

2018-05-23 17:03 UTC, alxdarksage commented on src/test/java/org/sagebionetworks/bridge/sdk/integration/AccountSummarySearchTest.java
> +        }
Moved these to @BeforeClass.

2018-05-23 21:59 UTC, DwayneJengSage approved these changes

2018-05-23 22:14 UTC, merged