Testing changes to app config API
Sage-Bionetworks/BridgeIntegrationTests pull request #274
Opened 2018-06-21 23:18 UTC by alxdarksage

2018-06-25 23:31 UTC, DwayneJengSage requested changes

2018-06-25 23:31 UTC, DwayneJengSage commented on src/test/java/org/sagebionetworks/bridge/sdk/integration/AppConfigTest.java
> +            adminApi.deleteAppConfig(config.getGuid(), true).execute();
This test works if the study is empty, but will fail if the study has pre-existing app configs (used for manual testing and local testing). This will also fail if the test fails to physically delete an app config after logically deleting it.

It would be better to keep track of the app configs created by the test and then delete only those.

2018-06-25 23:31 UTC, DwayneJengSage commented on src/test/java/org/sagebionetworks/bridge/sdk/integration/AppConfigTest.java
> +        assertTrue(countAfterDelete < updatedCount);
Would it be better to get by guid and verify that it throws a 404 not found?

2018-06-27 17:09 UTC, alxdarksage commented on src/test/java/org/sagebionetworks/bridge/sdk/integration/AppConfigTest.java
> +            adminApi.deleteAppConfig(config.getGuid(), true).execute();
Changed this to track the configs made by the test, and only deleting those.

2018-06-27 17:23 UTC, alxdarksage commented on src/test/java/org/sagebionetworks/bridge/sdk/integration/AppConfigTest.java
> +        assertTrue(countAfterDelete < updatedCount);
Changed to do this.

2018-06-29 16:51 UTC, merged