Update survey deletion behavior.
Sage-Bionetworks/BridgeIntegrationTests pull request #277
Opened 2018-07-05 23:34 UTC by alxdarksage

2018-07-23 23:19 UTC, DwayneJengSage requested changes

2018-07-23 23:19 UTC, DwayneJengSage commented on src/test/java/org/sagebionetworks/bridge/sdk/integration/SurveyTest.java
> +        SurveyList surveyResourceList = workerApi.getAllPublishedSurveys(IntegTestUtils.STUDY_ID, false).execute().body();
Test for includeDeleted=true?

2018-07-23 23:19 UTC, DwayneJengSage commented on src/test/java/org/sagebionetworks/bridge/sdk/integration/SurveyTest.java
> +        SurveysApi surveysApi = developer.getClient(SurveysApi.class);
What about getPublishedSurveyVersion()? getMostRecentSurveyVersion()?

2018-07-23 23:19 UTC, DwayneJengSage commented on src/test/java/org/sagebionetworks/bridge/sdk/integration/SurveyTest.java
> +                surveysApi.getAllVersionsOfSurvey(key.getGuid(), false).execute().body().getItems().size());
We happen to know that the expected counts here are 2 and 1 respectively. Would it be better to just use thocse constants?

2018-07-24 20:49 UTC, alxdarksage commented on src/test/java/org/sagebionetworks/bridge/sdk/integration/SurveyTest.java
> +        SurveyList surveyResourceList = workerApi.getAllPublishedSurveys(IntegTestUtils.STUDY_ID, false).execute().body();
Added

2018-07-25 16:40 UTC, alxdarksage commented on src/test/java/org/sagebionetworks/bridge/sdk/integration/SurveyTest.java
> +        SurveysApi surveysApi = developer.getClient(SurveysApi.class);
These should not take an includeDeleted flag; they should resolve to the most recent version or most recently published version that is not (logically) deleted. Removed the flag from the SDK (see new PR, the first PR has been merged) and adjusted the tests here to reflect this. Note the server did not have this flag in its routes or other code for these calls.

2018-07-25 21:15 UTC, DwayneJengSage requested changes

2018-07-25 21:15 UTC, DwayneJengSage commented on src/test/java/org/sagebionetworks/bridge/sdk/integration/SurveyTest.java
> +        } catch(EntityNotFoundException e) {
Need a fail() here. Otherwise, if this doesn't throw, we'll never know.

2018-07-25 22:04 UTC, alxdarksage commented on src/test/java/org/sagebionetworks/bridge/sdk/integration/SurveyTest.java
> +        } catch(EntityNotFoundException e) {
Added here (and one other place in test).

2018-07-25 22:06 UTC, DwayneJengSage approved these changes

2018-07-25 22:09 UTC, merged