Change test to switch admin between studies.
Sage-Bionetworks/BridgeIntegrationTests pull request #285
Opened 2018-08-22 17:47 UTC by alxdarksage

2018-08-24 21:43 UTC, DwayneJengSage requested changes

2018-08-24 21:43 UTC, DwayneJengSage commented on src/test/java/org/sagebionetworks/bridge/sdk/integration/SurveyTest.java
> +            surveysApi.deleteSurvey(oneSurvey.getGuid(), oneSurvey.getCreatedOn(), true).execute();
Do we want to delete this try-catch? If we do, then if deleting a survey fails, the test won't attempt to delete any of the other surveys.

2018-08-24 21:43 UTC, DwayneJengSage commented on src/test/java/org/sagebionetworks/bridge/sdk/integration/SurveyTest.java
>              adminSurveysApi.deleteSurvey(retSurvey.getGuid(), retSurvey.getCreatedOn(), true).execute();
Do we also need to change the client here as well?

2018-08-24 22:01 UTC, alxdarksage commented on src/test/java/org/sagebionetworks/bridge/sdk/integration/SurveyTest.java
> +            surveysApi.deleteSurvey(oneSurvey.getGuid(), oneSurvey.getCreatedOn(), true).execute();
It's also not consistent with what we're doing elsewhere... restored the try/catch block.

2018-08-24 22:05 UTC, alxdarksage commented on src/test/java/org/sagebionetworks/bridge/sdk/integration/SurveyTest.java
>              adminSurveysApi.deleteSurvey(retSurvey.getGuid(), retSurvey.getCreatedOn(), true).execute();
It is confusing that we have these two clients to do manipulate surveys as an admin... I removed one of them (SurveysApi) and I'm using the ForAdminsApi for both these calls now.

2018-08-24 23:30 UTC, DwayneJengSage requested changes

2018-08-24 23:30 UTC, DwayneJengSage commented on src/test/java/org/sagebionetworks/bridge/sdk/integration/SurveyTest.java
> +    //private static SurveysApi adminSurveysApi;
Nitpick: Remove commented variable.

2018-08-24 23:30 UTC, DwayneJengSage commented on src/test/java/org/sagebionetworks/bridge/sdk/integration/SurveyTest.java
> +            adminsApi.adminChangeStudy(new SignIn().study("api")).execute();
I'm a little confused here. In some places, we call admin.getClient(). In other places, we call the adminsApi directly.

2018-08-27 17:08 UTC, alxdarksage commented on src/test/java/org/sagebionetworks/bridge/sdk/integration/SurveyTest.java
> +    //private static SurveysApi adminSurveysApi;
removed

2018-08-27 17:10 UTC, alxdarksage commented on src/test/java/org/sagebionetworks/bridge/sdk/integration/SurveyTest.java
> +            adminsApi.adminChangeStudy(new SignIn().study("api")).execute();
You're right, all these delete APIs are on the ForAdminsApi client, changed all of these to use it.

2018-08-27 22:56 UTC, DwayneJengSage approved these changes

2018-08-28 04:47 UTC, merged