Adjusting for the removal of the two synthetic events (adding one back as an automatic custom event).
Sage-Bionetworks/BridgeIntegrationTests pull request #291
Opened 2018-08-29 00:34 UTC by alxdarksage

2018-09-04 23:31 UTC, DwayneJengSage requested changes

2018-09-04 23:31 UTC, DwayneJengSage commented on src/test/java/org/sagebionetworks/bridge/sdk/integration/ActivityEventTest.java
>          assertNotNull(twoWeeksAfterEvent);
We'll need to clean up the automatic custom events in the api study (probably manually) and fix up this portion of the test.

2018-09-05 15:45 UTC, alxdarksage commented on src/test/java/org/sagebionetworks/bridge/sdk/integration/ActivityEventTest.java
>          assertNotNull(twoWeeksAfterEvent);
Changed the event key.

2018-09-05 18:19 UTC, DwayneJengSage approved these changes

2018-09-05 18:21 UTC, merged