Withdraw from study
Sage-Bionetworks/BridgeIntegrationTests pull request #296
Opened 2018-09-10 20:08 UTC by alxdarksage

Adding methods to test.

2018-09-10 20:50 UTC, DwayneJengSage commented on src/test/java/org/sagebionetworks/bridge/sdk/integration/ConsentTest.java
> +            testUser.getClient(ForConsentedUsersApi.class).withdrawFromStudy(withdrawal).execute();
This test previously tested the researcher withdraw API. Now it tests the user's withdraw API. Was this intentional?

2018-09-10 23:29 UTC, DwayneJengSage requested changes

2018-09-10 23:29 UTC, DwayneJengSage commented on src/test/java/org/sagebionetworks/bridge/sdk/integration/ConsentTest.java
> +            testUser.getClient(ForConsentedUsersApi.class).withdrawFromStudy(withdrawal).execute();
Test for researcher withdrawal was deleted. Both tests have the user withdrawing themselves.

2018-09-10 23:43 UTC, alxdarksage commented on src/test/java/org/sagebionetworks/bridge/sdk/integration/ConsentTest.java
> +            testUser.getClient(ForConsentedUsersApi.class).withdrawFromStudy(withdrawal).execute();
Okay, updated the second test to withdraw the user through the participant API, not the user-facing API in both places.

2018-09-11 00:04 UTC, DwayneJengSage approved these changes

2018-09-11 00:07 UTC, merged