Add integration test for substudy auth checks.
Sage-Bionetworks/BridgeIntegrationTests pull request #325
Opened 2018-11-20 22:57 UTC by alxdarksage

2018-11-28 04:20 UTC, DwayneJengSage requested changes

2018-11-28 04:20 UTC, DwayneJengSage commented on src/test/java/org/sagebionetworks/bridge/sdk/integration/SubstudyFilteringTest.java
> +            }
If you pass in substudyA, this will return if it finds an account with substudyA+any other study. Since we control the accounts, it might be better to ceck for set equality instead of contains all.

2018-11-28 04:20 UTC, DwayneJengSage commented on src/test/java/org/sagebionetworks/bridge/sdk/integration/SubstudyFilteringTest.java
> +            }
Does the order of deleting users vs substudies matter? If so, are we sure these two Afters will run in the correct order?

2018-11-28 04:20 UTC, DwayneJengSage commented on src/test/java/org/sagebionetworks/bridge/sdk/integration/SubstudyFilteringTest.java
> +    }
createAdmin() and createUser() are almost identical. Can we consolidate them?

2018-11-28 20:46 UTC, alxdarksage commented on src/test/java/org/sagebionetworks/bridge/sdk/integration/SubstudyFilteringTest.java
> +            }
This is a weird one. It should matter. If you delete substudies while they are associated to users, you'll get an error, but running the test with the @After methods in either order, this doesn't happen. Maybe they're alphabetized or something.  I combined the methods so whatever is ordering them, if it breaks, it won't break the test.

2018-11-28 20:46 UTC, alxdarksage commented on src/test/java/org/sagebionetworks/bridge/sdk/integration/SubstudyFilteringTest.java
> +            }
This is a weird one. It should matter. If you delete substudies while they are associated to users, you'll get an error, but running the test with the @after methods in either order, this doesn't happen. Maybe they're alphabetized or something. I combined the methods so whatever is ordering them, if it breaks, it won't break the test.

2018-11-28 20:58 UTC, alxdarksage commented on src/test/java/org/sagebionetworks/bridge/sdk/integration/SubstudyFilteringTest.java
> +    }
consolidated.

2018-11-29 00:53 UTC, DwayneJengSage approved these changes
Looks good. Just one minor note.

2018-11-29 00:53 UTC, DwayneJengSage commented on src/test/java/org/sagebionetworks/bridge/sdk/integration/SubstudyFilteringTest.java
> +            }
Minor: equals() should do what you want it to do https://docs.oracle.com/javase/7/docs/api/java/util/Set.html#equals(java.lang.Object)

2018-11-29 21:52 UTC, alxdarksage commented on src/test/java/org/sagebionetworks/bridge/sdk/integration/SubstudyFilteringTest.java
> +            }
Updated to use equals method

2018-11-29 22:47 UTC, DwayneJengSage approved these changes

2018-11-29 22:48 UTC, merged