Two new survey constraints: YearMonth and PostalCode.
Sage-Bionetworks/BridgeIntegrationTests pull request #329
Opened 2019-01-11 17:30 UTC by alxdarksage

2019-02-08 00:36 UTC, DwayneJengSage requested changes

2019-02-08 00:36 UTC, DwayneJengSage commented on src/test/java/org/sagebionetworks/bridge/sdk/integration/TestSurvey.java
> +        c11.setDataType(DataType.YEARMONTH);
Should we add earliest, latest, and allowFuture here, just to get coverage on all attributes?

2019-02-08 00:36 UTC, DwayneJengSage commented on src/test/java/org/sagebionetworks/bridge/sdk/integration/TestSurvey.java
> +        elements.add(postalCodeQuestion);
Is there a test somewhere where we receive the survey back from the server to verify round-trip survey marshalling?  (Including all the new attributes: allowFuture, earliest, latest, country code, and sparse zip codes?)

2019-02-08 21:54 UTC, alxdarksage commented on src/test/java/org/sagebionetworks/bridge/sdk/integration/TestSurvey.java
> +        elements.add(postalCodeQuestion);
I added a test like this because it doesn't exist, moved one test into it, and found a couple of bugs in earlier mappings for earlier constraints that were added. I fixed those and bumped the version of the SDK, and now I am importing that version (the test also now includes a test of these new constraint types).

2019-02-08 21:56 UTC, alxdarksage commented on src/test/java/org/sagebionetworks/bridge/sdk/integration/TestSurvey.java
> +        c11.setDataType(DataType.YEARMONTH);
Yes, added and then added to test, described below. That test in turn led me to add a few more of these fields to the TestSurvey that were previously left null.

2019-02-12 00:59 UTC, DwayneJengSage approved these changes
Looks good. Just one comment about timezones, not a blocker for this pull request.

2019-02-12 00:59 UTC, DwayneJengSage commented on src/test/java/org/sagebionetworks/bridge/sdk/integration/TestSurvey.java
> +    public static final DateTime DATETIME_EARLIEST_VALUE = DateTime.parse("2000-01-01").withZone(DateTimeZone.UTC);
Should we test that this works with a timezone other than UTC? (If it doesn't work, we should file a JIRA to figure out why as a separate code change.)

2019-02-12 19:01 UTC, merged