Verify criteria filtering is working with substudy memberships.
Sage-Bionetworks/BridgeIntegrationTests pull request #334
Opened 2019-02-20 20:38 UTC by alxdarksage

2019-02-23 00:41 UTC, DwayneJengSage requested changes

2019-02-23 00:41 UTC, DwayneJengSage commented on src/test/java/org/sagebionetworks/bridge/sdk/integration/SubstudyFilteringTest.java
> +            assertFalse(abList.getItems().isEmpty());
There may be other schedules in the api study. You should created a label unique to this test run and filter the activities on label.

2019-02-27 00:48 UTC, alxdarksage commented on src/test/java/org/sagebionetworks/bridge/sdk/integration/SubstudyFilteringTest.java
> +            assertFalse(abList.getItems().isEmpty());
Updated

2019-02-28 00:36 UTC, DwayneJengSage approved these changes

2019-02-28 15:53 UTC, merged