Updating tests.
Sage-Bionetworks/BridgeIntegrationTests pull request #338
Opened 2019-03-08 21:53 UTC by alxdarksage

For Bridge PR #1834.

2019-04-03 04:05 UTC, DwayneJengSage requested changes

2019-04-03 04:05 UTC, DwayneJengSage commented on src/test/java/org/sagebionetworks/bridge/sdk/integration/ConsentTest.java
> +            assertNotNull(sigFromServer.getSignedOn());
Should we also check withdrewOn after withdrawing?

2019-04-04 18:51 UTC, alxdarksage commented on src/test/java/org/sagebionetworks/bridge/sdk/integration/ConsentTest.java
> +            assertNotNull(sigFromServer.getSignedOn());
Added a check (researcher account retrieves the participant and verifies the history object for this signature has a withdrawn timestamp).

2019-04-04 21:25 UTC, DwayneJengSage requested changes

2019-04-04 21:25 UTC, DwayneJengSage commented on src/test/java/org/sagebionetworks/bridge/sdk/integration/ConsentTest.java
> +            assertTrue( history.get(0).getWithdrewOn().isAfter(DateTime.now().minusMinutes(2)) );
Jenkins clock skew can be as high as 10 minutes. This test may fail sporadically.

2019-04-04 21:25 UTC, DwayneJengSage commented on src/test/java/org/sagebionetworks/bridge/sdk/integration/SessionTest.java
> +        assertTrue(session.getCreatedOn().isAfter(startOfTest));
Similarly, this is likely to fail sporadically (and again later in this same test).

2019-04-04 21:51 UTC, DwayneJengSage approved these changes

2019-04-04 23:07 UTC, merged