Enhancing ITP to accept email-based accounts.
Sage-Bionetworks/BridgeIntegrationTests pull request #339
Opened 2019-03-11 23:13 UTC by alxdarksage

2019-03-25 21:42 UTC, DwayneJengSage requested changes

2019-03-25 21:42 UTC, DwayneJengSage commented on src/test/java/org/sagebionetworks/bridge/sdk/integration/IntentToParticipateTest.java
> +            fail("This should not have thrown an exception");
Don't do this. This masks any exception thrown by the test as well as any assert.

2019-03-25 21:42 UTC, DwayneJengSage commented on src/test/java/org/sagebionetworks/bridge/sdk/integration/IntentToParticipateTest.java
> +            fail("This should not have thrown an exception");
Similarly here.

2019-03-25 21:45 UTC, DwayneJengSage requested changes
Also, do we want to add appInstallLinkTemplate to StudyTest.crudStudy()?

2019-03-26 18:08 UTC, alxdarksage commented on src/test/java/org/sagebionetworks/bridge/sdk/integration/IntentToParticipateTest.java
> +            fail("This should not have thrown an exception");
Removed

2019-03-26 18:08 UTC, alxdarksage commented on src/test/java/org/sagebionetworks/bridge/sdk/integration/IntentToParticipateTest.java
> +            fail("This should not have thrown an exception");
Removed

2019-03-26 23:38 UTC, DwayneJengSage approved these changes

2019-03-27 03:04 UTC, merged