Tests of substudy partitioning of reports.
Sage-Bionetworks/BridgeIntegrationTests pull request #343
Opened 2019-04-01 22:32 UTC by alxdarksage

2019-04-09 23:24 UTC, DwayneJengSage requested changes

2019-04-09 23:24 UTC, DwayneJengSage commented on src/test/java/org/sagebionetworks/bridge/sdk/integration/ReportTest.java
> +        assertEquals(2, list.getItems().size());
Instead of just counting the reports, we should also validate the content (most notably the substudyIDs).

2019-04-09 23:24 UTC, DwayneJengSage commented on src/test/java/org/sagebionetworks/bridge/sdk/integration/ReportTest.java
> +        data1.setSubstudyIds(ImmutableList.of(substudy1.getId()));
We should also check the workers can get reports back with substudies.

2019-04-09 23:24 UTC, DwayneJengSage commented on src/test/java/org/sagebionetworks/bridge/sdk/integration/ReportTest.java
> +        ReportIndex index = reportsApi.getStudyReportIndex(reportId).execute().body();
Should there be an equivalent test for getParticipantReportIndex()?

2019-04-11 20:55 UTC, alxdarksage commented on src/test/java/org/sagebionetworks/bridge/sdk/integration/ReportTest.java
> +        assertEquals(2, list.getItems().size());
Once set with the first report, substudy IDs are only persisted on the index, for all the records, so that field is null when you retrieve the reports. I did add tests of all of this.

I guess we could set those as read-only values in the report data records as well when reading from the server, but it didn't come up as something useful when implementing UI to create and edit these.

2019-04-11 21:37 UTC, alxdarksage commented on src/test/java/org/sagebionetworks/bridge/sdk/integration/ReportTest.java
> +        data1.setSubstudyIds(ImmutableList.of(substudy1.getId()));
Added

2019-04-11 21:53 UTC, alxdarksage commented on src/test/java/org/sagebionetworks/bridge/sdk/integration/ReportTest.java
> +        ReportIndex index = reportsApi.getStudyReportIndex(reportId).execute().body();
Added

2019-04-11 22:04 UTC, DwayneJengSage approved these changes

2019-04-11 23:03 UTC, merged