BRIDGE-2322: Verify that consent adds data groups/substudies and removed data groups on withdrawal.
Sage-Bionetworks/BridgeIntegrationTests pull request #344
Opened 2019-04-03 23:19 UTC by alxdarksage

2019-04-09 23:35 UTC, DwayneJengSage requested changes

2019-04-09 23:35 UTC, DwayneJengSage commented on src/test/java/org/sagebionetworks/bridge/sdk/integration/ConsentTest.java
> +    @Ignore
We should remove all of the ignores.

2019-04-09 23:35 UTC, DwayneJengSage commented on src/test/java/org/sagebionetworks/bridge/sdk/integration/ConsentTest.java
> +            subpop.setDataGroupsAssignedWhileConsented(dataGroupList);
We should also verify that we can get these back from getSubpop().

2019-04-09 23:35 UTC, DwayneJengSage commented on src/test/java/org/sagebionetworks/bridge/sdk/integration/ConsentTest.java
> +                + "   \"imageData\":\"" + FAKE_IMAGE_DATA + "\",\n" + "   \"imageMimeType\":\"image/fake\"\n" + "}";
The other way is more readable.

2019-04-09 23:35 UTC, DwayneJengSage commented on src/test/java/org/sagebionetworks/bridge/sdk/integration/ConsentTest.java
> +                    .scope(SharingScope.SPONSORS_AND_PARTNERS);
For future reference, can you refrain from reformatting entire files. It makes the diff difficult to read (even _with_ the Hide Whitespace Changes feature).

2019-04-09 23:35 UTC, DwayneJengSage commented on src/test/java/org/sagebionetworks/bridge/sdk/integration/ConsentTest.java
> +            e.printStackTrace();
Don't do this. This suppresses test failures.

2019-04-09 23:35 UTC, DwayneJengSage commented on src/test/java/org/sagebionetworks/bridge/sdk/integration/ConsentTest.java
> +                substudy = substudies.getItems().get(0);
We should always create a new substudy instead of trying to hijack an existing one. Hijacking existing substudies means we may interfere with other tests. (Especially if we delete them at the end of the test.)

2019-04-09 23:35 UTC, DwayneJengSage commented on src/test/java/org/sagebionetworks/bridge/sdk/integration/ConsentTest.java
> +            }
If the subpop fails to create, subpop will be non-null, but subpop.getGuid() will be null. We should check for subpop.getGuid() in addition.

2019-04-12 16:45 UTC, alxdarksage commented on src/test/java/org/sagebionetworks/bridge/sdk/integration/ConsentTest.java
> +    @Ignore
Ack! Removed.

2019-04-12 16:51 UTC, alxdarksage commented on src/test/java/org/sagebionetworks/bridge/sdk/integration/ConsentTest.java
> +            subpop.setDataGroupsAssignedWhileConsented(dataGroupList);
Added this to the SubpopulationTest.

2019-04-12 16:52 UTC, alxdarksage commented on src/test/java/org/sagebionetworks/bridge/sdk/integration/ConsentTest.java
> +            e.printStackTrace();
Yes, like @Ignore this should have been removed. Removed.

2019-04-12 20:20 UTC, alxdarksage commented on src/test/java/org/sagebionetworks/bridge/sdk/integration/ConsentTest.java
> +                + "   \"imageData\":\"" + FAKE_IMAGE_DATA + "\",\n" + "   \"imageMimeType\":\"image/fake\"\n" + "}";
This (and the formatting you complain about below) were due to IDE formatting. Changed this to something more readable than this.

2019-04-12 20:21 UTC, alxdarksage commented on src/test/java/org/sagebionetworks/bridge/sdk/integration/ConsentTest.java
> +                    .scope(SharingScope.SPONSORS_AND_PARTNERS);
See above, sometime the code formatter does its thing. I'll do my best to avoid reformatting code.

2019-04-12 20:49 UTC, alxdarksage commented on src/test/java/org/sagebionetworks/bridge/sdk/integration/ConsentTest.java
> +                substudy = substudies.getItems().get(0);
Sure. Changed with a delete of the substudy added to cleanup. Did the same in the new subpopulation test changes.

2019-04-12 20:55 UTC, alxdarksage commented on src/test/java/org/sagebionetworks/bridge/sdk/integration/ConsentTest.java
> +            }
Yes, added this check.

2019-04-12 21:55 UTC, DwayneJengSage approved these changes

2019-04-12 22:26 UTC, merged