Adding some tests to cover functionality that was being tested in BridgePF by starting full Spring context
Sage-Bionetworks/BridgeIntegrationTests pull request #350
Opened 2019-04-17 00:42 UTC by alxdarksage

2019-04-17 20:47 UTC, DwayneJengSage requested changes

2019-04-17 20:47 UTC, DwayneJengSage commented on src/test/java/org/sagebionetworks/bridge/sdk/integration/ScheduledActivityTest.java
> +        schema.setSchemaId("schemaId"+RandomStringUtils.randomAlphabetic(4));
We should use Tests.randomIdentifier(), so we tag the schema ID with the test that created it.

2019-04-17 20:47 UTC, DwayneJengSage commented on src/test/java/org/sagebionetworks/bridge/sdk/integration/ScheduledActivityTest.java
> +        schemaKeys = schemasApi.createOrUpdateUploadSchema(schema).execute().body();
Minor: createUploadSchema() is preferred over createOrUpdateUploadSchema().

2019-04-17 20:47 UTC, DwayneJengSage commented on src/test/java/org/sagebionetworks/bridge/sdk/integration/ScheduledActivityTest.java
> +            }
Is there any reason why this delete is inside the try, but the other delete is outside?

2019-04-17 20:47 UTC, DwayneJengSage commented on src/test/java/org/sagebionetworks/bridge/sdk/integration/ScheduledActivityTest.java
> +        assertEquals(10, list.getItems().size());
There may be other scheduled activities using that task ID. Should we create a unique activity label and filter on that label?

Similarly for getTaskHistory().

2019-04-17 20:47 UTC, DwayneJengSage commented on src/test/java/org/sagebionetworks/bridge/sdk/integration/ScheduledActivityTest.java
> +        assertTrue(list4.getItems().isEmpty());
Similarly, this may pick up other tasks with the same task ID.

Similarly for getTaskHistory().

2019-04-17 20:47 UTC, DwayneJengSage commented on src/test/java/org/sagebionetworks/bridge/sdk/integration/ScheduledActivityTest.java
> +            activityGuid = act.getGuid().split(":")[0];
Are we sure this is what we want? This basically uses the activityGuid from the last activity in the list, which might not be the one we're looking for. We should set a unique activity label and filter on activity label.

2019-04-17 23:09 UTC, alxdarksage commented on src/test/java/org/sagebionetworks/bridge/sdk/integration/ScheduledActivityTest.java
> +            guids.add(act.getGuid());
Added.

2019-04-17 23:09 UTC, alxdarksage commented on src/test/java/org/sagebionetworks/bridge/sdk/integration/ScheduledActivityTest.java
> +        schema.setSchemaId("schemaId"+RandomStringUtils.randomAlphabetic(4));
Changed

2019-04-17 23:10 UTC, alxdarksage commented on src/test/java/org/sagebionetworks/bridge/sdk/integration/ScheduledActivityTest.java
> +        schemaKeys = schemasApi.createOrUpdateUploadSchema(schema).execute().body();
Changed

2019-04-17 23:11 UTC, alxdarksage commented on src/test/java/org/sagebionetworks/bridge/sdk/integration/ScheduledActivityTest.java
> +            }
No, the admin isn't deleted, it can come after the finally block. Moved.

2019-04-17 23:18 UTC, alxdarksage commented on src/test/java/org/sagebionetworks/bridge/sdk/integration/ScheduledActivityTest.java
> +        assertEquals(10, list.getItems().size());
All the scheduled activities are created for a user that is created for this specific test, so they should never conflict even if other users have scheduled activities with the same task ID.

2019-04-17 23:18 UTC, alxdarksage commented on src/test/java/org/sagebionetworks/bridge/sdk/integration/ScheduledActivityTest.java
> +        assertTrue(list4.getItems().isEmpty());
See above

2019-04-18 19:25 UTC, alxdarksage commented on src/test/java/org/sagebionetworks/bridge/sdk/integration/ScheduledActivityTest.java
> +        assertEquals(10, list.getItems().size());
I rewrote all of these to filter out tasks with the wrong label (using runId) to avoid this problem. Verified by leaving all the schedule plans from one test and re-running the test suite again.

2019-04-18 19:26 UTC, alxdarksage commented on src/test/java/org/sagebionetworks/bridge/sdk/integration/ScheduledActivityTest.java
> +            activityGuid = act.getGuid().split(":")[0];
We now filter before retrieving this value from the list, so it will be correct.

2019-04-18 21:12 UTC, alxdarksage commented on src/test/java/org/sagebionetworks/bridge/sdk/integration/ScheduledActivityTest.java
> +            activityGuid = act.getGuid().split(":")[0];
Now this is done after filtering on the label, so it is the GUID that we want.

2019-04-18 22:32 UTC, DwayneJengSage requested changes

2019-04-18 22:32 UTC, DwayneJengSage commented on src/test/java/org/sagebionetworks/bridge/sdk/integration/ScheduledActivityTest.java
> +        assertEquals(16, list.getItems().size());
We should check request params.

2019-04-18 22:32 UTC, DwayneJengSage commented on src/test/java/org/sagebionetworks/bridge/sdk/integration/ScheduledActivityTest.java
> +        ForwardCursorScheduledActivityList list = filterPages(false, (offsetKey) ->
Shouldn't this be true, since we expect at least 2 pages?

2019-04-18 22:32 UTC, DwayneJengSage commented on src/test/java/org/sagebionetworks/bridge/sdk/integration/ScheduledActivityTest.java
> +        }
Should this have pagination logic?

2019-04-19 00:06 UTC, alxdarksage commented on src/test/java/org/sagebionetworks/bridge/sdk/integration/ScheduledActivityTest.java
> +        assertEquals(16, list.getItems().size());
Added

2019-04-19 00:06 UTC, alxdarksage commented on src/test/java/org/sagebionetworks/bridge/sdk/integration/ScheduledActivityTest.java
> +        ForwardCursorScheduledActivityList list = filterPages(false, (offsetKey) ->
Yes, changed to true

2019-04-19 00:11 UTC, alxdarksage commented on src/test/java/org/sagebionetworks/bridge/sdk/integration/ScheduledActivityTest.java
> +        }
This API is not paged. We limit the date range to 32 days but that's it.

2019-04-19 19:18 UTC, DwayneJengSage requested changes

2019-04-19 19:18 UTC, DwayneJengSage commented on src/test/java/org/sagebionetworks/bridge/sdk/integration/ScheduledActivityTest.java
> +        ForwardCursorScheduledActivityList list = filterPages(false, (offsetKey) ->
This should be true, since we expect at least 2 pages.

2019-04-22 19:20 UTC, DwayneJengSage approved these changes

2019-04-22 20:22 UTC, merged