Porting a couple of tests of scheduling from BridgePF to the integration tests.
Sage-Bionetworks/BridgeIntegrationTests pull request #361
Opened 2019-05-31 18:07 UTC by alxdarksage

They are a little different because we can't fix time on the server, but demonstrate that time zones are handled in a consistent fashion.

2019-06-03 07:01 UTC, DwayneJengSage requested changes

2019-06-03 07:01 UTC, DwayneJengSage commented on src/test/java/org/sagebionetworks/bridge/sdk/integration/ScheduledActivityRecurringTest.java
> +        assertEquals(mtz3, activities.getItems().get(2).getScheduledOn().toString());
This test assumes there are no other schedules in the study, which might not be the case. It would be better to use a label and then filter on that label.

2019-06-06 19:59 UTC, alxdarksage commented on src/test/java/org/sagebionetworks/bridge/sdk/integration/ScheduleActivityOnceTest.java
> +        }
Switched to the use of a label and filtering

2019-06-06 20:12 UTC, alxdarksage commented on src/test/java/org/sagebionetworks/bridge/sdk/integration/ScheduledActivityRecurringTest.java
> +        assertEquals(mtz3, activities.getItems().get(2).getScheduledOn().toString());
Filtering on schedule guid

2019-06-06 22:26 UTC, DwayneJengSage commented
Should there also be an update to ScheduledActivityRecurringTest?

2019-06-07 23:30 UTC, alxdarksage commented
Updated to include activity filtering in ScheduledActivityRecurringTest test.

2019-06-10 23:09 UTC, DwayneJengSage approved these changes

2019-06-10 23:16 UTC, merged