Templates test
Sage-Bionetworks/BridgeIntegrationTests pull request #365
Opened 2019-06-25 21:50 UTC by alxdarksage

2019-06-26 23:45 UTC, DwayneJengSage requested changes

2019-06-26 23:45 UTC, DwayneJengSage commented on src/test/java/org/sagebionetworks/bridge/sdk/integration/TemplateTest.java
> +        assertTrue(list.getItems().isEmpty());
Long-term, this might come back to bite us. When we eventually wire up these templates to the actual emails, and we have integ tests that test these scenarios, we may end up needing these template to exist and be not deleted.

It would be better if you check the list and make sure none of them match the expected template guid.

2019-06-27 17:23 UTC, alxdarksage commented on src/test/java/org/sagebionetworks/bridge/sdk/integration/TemplateTest.java
> +        assertTrue(list.getItems().isEmpty());
Very true. Changed both places (find and don't find in results).

2019-06-28 00:03 UTC, DwayneJengSage approved these changes

2019-06-28 18:46 UTC, merged