Adding test for year type survey question.
Sage-Bionetworks/BridgeIntegrationTests pull request #391
Opened 2019-09-27 19:27 UTC by alxdarksage

2019-09-27 23:23 UTC, DwayneJengSage requested changes

2019-09-27 23:23 UTC, DwayneJengSage commented on src/test/java/org/sagebionetworks/bridge/sdk/integration/SurveyTest.java
> +        assertTrue(dateConstraints.isAllowFuture()); // true by default
Nitpick: allowFuture is false by default. This field is true because in TestSurvey, we set it to true. (Here and in a few other places in this test.)

2019-09-27 23:23 UTC, DwayneJengSage commented on src/test/java/org/sagebionetworks/bridge/sdk/integration/TestSurvey.java
> +        yc.setLatestValue("2020");
For completeness, should we also set the EarliestValue?

2019-09-27 23:23 UTC, DwayneJengSage commented on src/test/java/org/sagebionetworks/bridge/sdk/integration/TestSurvey.java
> +        yearQuestion.setUiHint(UIHint.SLIDER);
Similarly, for completeness, should we also test our new UIHint.YEAR?

2019-09-30 20:11 UTC, alxdarksage commented on src/test/java/org/sagebionetworks/bridge/sdk/integration/SurveyTest.java
> +        assertTrue(dateConstraints.isAllowFuture()); // true by default
I've consistently changed the time-based constraints to flip the defaults, and then test that they are flipped.

2019-09-30 20:11 UTC, alxdarksage commented on src/test/java/org/sagebionetworks/bridge/sdk/integration/TestSurvey.java
> +        yc.setLatestValue("2020");
Added

2019-09-30 20:17 UTC, DwayneJengSage approved these changes

2019-09-30 20:17 UTC, merged