Checking for synapse user ID
Sage-Bionetworks/BridgeIntegrationTests pull request #395
Opened 2019-10-30 17:20 UTC by alxdarksage

2019-10-30 22:24 UTC, DwayneJengSage reviewed
What about the new get user by synapse ID APIs?

2019-10-31 23:21 UTC, DwayneJengSage requested changes
What about the new get user by synapse ID APIs?

2019-11-01 20:00 UTC, alxdarksage commented
Added tests for the two getParticipantBySynapseUserId() methods (one for worker, one for researcher).

2019-11-04 20:12 UTC, DwayneJengSage approved these changes

2019-11-04 20:55 UTC, merged