Adding test of switching between studies.
Sage-Bionetworks/BridgeIntegrationTests pull request #400
Opened 2019-11-19 17:30 UTC by alxdarksage

2019-11-20 01:51 UTC, DwayneJengSage requested changes

2019-11-20 01:51 UTC, DwayneJengSage commented on src/test/java/org/sagebionetworks/bridge/sdk/integration/OAuthTest.java
> +        assertEquals(ImmutableSet.of(STUDY_ID, SHARED_STUDY_ID), ImmutableSet.copyOf(studyIds));
Would it make more sens to call Collectors.toSet() instead of converting it into a list then converting it into a set?

2019-11-20 01:51 UTC, DwayneJengSage commented on src/test/java/org/sagebionetworks/bridge/sdk/integration/OAuthTest.java
> +        admin.signOut();
Should this be in a finally (or possibly an after) to ensure the admin doesn't stay signed in the shared study?

2019-11-20 20:05 UTC, alxdarksage commented on src/test/java/org/sagebionetworks/bridge/sdk/integration/OAuthTest.java
> +        assertEquals(ImmutableSet.of(STUDY_ID, SHARED_STUDY_ID), ImmutableSet.copyOf(studyIds));
Definitely, changed this.

2019-11-20 20:05 UTC, alxdarksage commented on src/test/java/org/sagebionetworks/bridge/sdk/integration/OAuthTest.java
> +        admin.signOut();
Moved to the @After block.

2019-11-20 22:07 UTC, DwayneJengSage requested changes

2019-11-20 22:07 UTC, DwayneJengSage commented on src/test/java/org/sagebionetworks/bridge/sdk/integration/SurveyTest.java
> -        assertTrue(multiValueConstraints.isRequired());
I think you have a merge error here (and in TestSurvey.java).

2019-11-20 22:30 UTC, alxdarksage commented on src/test/java/org/sagebionetworks/bridge/sdk/integration/SurveyTest.java
> -        assertTrue(multiValueConstraints.isRequired());
Yes, thanks for catching this. I didn't pull in develop branch changes before committing this.

2019-11-21 01:52 UTC, DwayneJengSage approved these changes

2019-11-21 18:36 UTC, merged