Introduce superadmin role
Sage-Bionetworks/BridgeIntegrationTests pull request #404
Opened 2019-11-25 19:34 UTC by alxdarksage

2019-11-28 02:52 UTC, DwayneJengSage requested changes

2019-11-28 02:52 UTC, DwayneJengSage commented on src/test/java/org/sagebionetworks/bridge/sdk/integration/SelfStudyTest.java
> -    @Test(expected = UnauthorizedException.class)
It looks like you accidentally deleted the test annotation from this test and the next.

2019-12-02 20:31 UTC, alxdarksage commented on src/test/java/org/sagebionetworks/bridge/sdk/integration/SelfStudyTest.java
> -    @Test(expected = UnauthorizedException.class)
I added the researcher expected exception (this would have failed after merging) and added a test to verify study admins can update their own studies as admins.

2019-12-03 02:06 UTC, DwayneJengSage approved these changes

2019-12-03 19:50 UTC, merged