Assessments1
Sage-Bionetworks/BridgeIntegrationTests pull request #412
Opened 2020-02-19 22:24 UTC by alxdarksage

2020-02-21 22:44 UTC, DwayneJengSage requested changes

2020-02-21 22:44 UTC, DwayneJengSage commented on src/test/java/org/sagebionetworks/bridge/sdk/integration/AssessmentTest.java
> +        assertEquals(unsavedAssessment.getTitle(), latest.getTitle());
Minor: Maybe save the original title to a separate variable that you can compare against here. At the very least, it means that if someone updates this test in the future and modifies unsavedAssessment, we won't get a weird failure here.

2020-02-25 20:01 UTC, alxdarksage commented on src/test/java/org/sagebionetworks/bridge/sdk/integration/AssessmentTest.java
> +                null, null, null, ImmutableList.of(markerTag), false).execute().body();
Added tests for all these paged APIs.

2020-02-25 20:01 UTC, alxdarksage commented on src/test/java/org/sagebionetworks/bridge/sdk/integration/AssessmentTest.java
> +        assertTrue(list.getItems().isEmpty());
Well, I created a bunch of stuff specifically to test the paging of that API, so I don't think we need to do it here.

2020-02-25 23:46 UTC, alxdarksage commented on src/test/java/org/sagebionetworks/bridge/sdk/integration/AssessmentTest.java
> +        assertTrue(list.getItems().isEmpty());
Added

2020-02-25 23:56 UTC, alxdarksage commented on src/test/java/org/sagebionetworks/bridge/sdk/integration/AssessmentTest.java
> +            adminSharedApi.deleteSharedAssessment(shared.getGuid(), true).execute().body();
Added

2020-02-25 23:58 UTC, alxdarksage commented on src/test/java/org/sagebionetworks/bridge/sdk/integration/AssessmentTest.java
> +        assertEquals(unsavedAssessment.getTitle(), latest.getTitle());
Moved this to a constant.

2020-02-27 20:57 UTC, DwayneJengSage requested changes

2020-02-27 20:57 UTC, DwayneJengSage commented on src/test/java/org/sagebionetworks/bridge/sdk/integration/AssessmentTest.java
> +        assertEquals(11, uniqueRevisionGuids.size());
For robustness, we should use a different guid set for getByGuid and getById. If one of these APIs isn't working it would get covered up by the other test. (Similarly for shared.)

2020-02-28 00:04 UTC, DwayneJengSage commented
As per comment on the Server pull request, if we call getAssessments with an assessment with multiple tags in the tag filter, will this return duplicate assessments? We'll need an Integ Test to verify.

2020-02-28 22:19 UTC, DwayneJengSage approved these changes

2020-03-02 21:04 UTC, alxdarksage commented on src/test/java/org/sagebionetworks/bridge/sdk/integration/AssessmentTest.java
> +        assertEquals(11, uniqueRevisionGuids.size());
I've changed this to separate the two sets of GUIDs so they don't mask each other.

2020-03-02 21:05 UTC, alxdarksage commented
I've added a test of the multiple tag scenario to verify it doesn't duplicate the results (the SQL was indeed wrong and needed to be changed).

2020-03-03 17:34 UTC, merged