Test updates for assessment resource links
Sage-Bionetworks/BridgeIntegrationTests pull request #415
Opened 2020-03-11 18:17 UTC by alxdarksage

2020-03-25 02:51 UTC, DwayneJengSage requested changes

2020-03-25 02:51 UTC, DwayneJengSage commented on src/test/java/org/sagebionetworks/bridge/sdk/integration/AssessmentResourceTest.java
> +    public void test() throws Exception {
Should we also have a test for deleteAssessmentResource and deleteSharedAssessmentResource for logical deletes?

2020-03-25 02:51 UTC, DwayneJengSage commented on src/test/java/org/sagebionetworks/bridge/sdk/integration/AssessmentResourceTest.java
> +        PagedExternalResourceList sharedResourcesPage = sharedAssessmentsApi.getSharedAssessmentResources(
What about a test for getSharedAssessmentResource() (singlular)?

2020-03-25 02:51 UTC, DwayneJengSage commented on src/test/java/org/sagebionetworks/bridge/sdk/integration/AssessmentResourceTest.java
> +        }
getSubstudy() throws if the substudy doesn't exist.

2020-03-25 02:51 UTC, DwayneJengSage commented on src/test/java/org/sagebionetworks/bridge/sdk/integration/AssessmentResourceTest.java
> +        id = randomIdentifier(AssessmentTest.class);
Should move id to the top of before(). That way, if the test fails in before(), you won't get a weird NullPointerException in after().

2020-03-25 02:51 UTC, DwayneJengSage commented on src/test/java/org/sagebionetworks/bridge/sdk/integration/AssessmentResourceTest.java
> +        // test paging values:
There's a comment here saying to test paging values, but no actual paging tests.

2020-03-25 16:29 UTC, alxdarksage commented on src/test/java/org/sagebionetworks/bridge/sdk/integration/AssessmentResourceTest.java
> +    public void test() throws Exception {
Added both of these at the end of the test.

2020-03-25 16:31 UTC, alxdarksage commented on src/test/java/org/sagebionetworks/bridge/sdk/integration/AssessmentResourceTest.java
> +        PagedExternalResourceList sharedResourcesPage = sharedAssessmentsApi.getSharedAssessmentResources(
Added this (it's also exercised as part of verifying that logically deleted items are still accessible if you have a direct reference to them).

2020-03-25 16:43 UTC, alxdarksage commented on src/test/java/org/sagebionetworks/bridge/sdk/integration/AssessmentResourceTest.java
> +        }
Refactored this to create if the call throws EntityNotFoundException. Tested this by deleting them and running the test. Also noted that otherDeveloper wasn't being cleaned up and not using the right class when creating the test email accounts for the developers, fixed all that.

2020-03-25 16:48 UTC, alxdarksage commented on src/test/java/org/sagebionetworks/bridge/sdk/integration/AssessmentResourceTest.java
> +        id = randomIdentifier(AssessmentTest.class);
moved

2020-03-25 17:30 UTC, alxdarksage commented on src/test/java/org/sagebionetworks/bridge/sdk/integration/AssessmentResourceTest.java
> +        // test paging values:
Added tests of the actual paging, not just the filtering arguments (at end of test).

2020-03-26 00:53 UTC, DwayneJengSage approved these changes

2020-03-26 16:40 UTC, merged