Tag API tests.
Sage-Bionetworks/BridgeIntegrationTests pull request #417
Opened 2020-03-19 23:26 UTC by alxdarksage

2020-03-25 03:48 UTC, DwayneJengSage requested changes

2020-03-25 03:48 UTC, DwayneJengSage commented on src/test/java/org/sagebionetworks/bridge/sdk/integration/TagTest.java
> +        assertFalse(allTags.containsKey("cat2") && allTags.get("cat2").contains("tag2.2"));
You should break up these assertFalse() statements. If the first clause is false, then the second clause will never be checked.

2020-03-25 03:48 UTC, DwayneJengSage commented on src/test/java/org/sagebionetworks/bridge/sdk/integration/TagTest.java
> +        assertFalse(allTags.containsKey("default") && allTags.get("default").contains("tag3"));
There might be other default tags in the api study. It would be better to merely check that your specific tag3 doesn't exist, rather than checking that there are no default tags.

2020-03-25 18:39 UTC, alxdarksage commented on src/test/java/org/sagebionetworks/bridge/sdk/integration/TagTest.java
> +        assertFalse(allTags.containsKey("cat2") && allTags.get("cat2").contains("tag2.2"));
The first part was just to prevent a null pointer exception before the second test... if the category doesn't exist, the specific tag in that category can't exist so it's okay if only the first part is evaluated... I can rewrite this to be clearer.

2020-03-26 00:59 UTC, DwayneJengSage approved these changes

2020-03-26 18:10 UTC, merged