Switching the integration tests from studies to apps
Sage-Bionetworks/BridgeIntegrationTests pull request #424
Opened 2020-05-01 15:38 UTC by alxdarksage

The IntegTestUtils package will need to be merged first, in addition to the SDK.

2020-05-05 00:48 UTC, DwayneJengSage requested changes

2020-05-05 00:48 UTC, DwayneJengSage commented on src/test/java/org/sagebionetworks/bridge/sdk/integration/ScheduledActivityRecurringTest.java
> +        assertEquals(3, activities.getItems().size());
Is there any reason this would change, if the only change was study->app?

We've flipped this back and forth several times in the past few months
https://github.com/Sage-Bionetworks/BridgeIntegrationTests/pull/408
https://github.com/Sage-Bionetworks/BridgeIntegrationTests/pull/411

It doesn't appear to fail in dev or staging. I think we should just leave this as is, and if it's an ongoing problem, we should file a Jira to track this down and figure it out once and for all.

2020-05-05 15:31 UTC, alxdarksage commented on src/test/java/org/sagebionetworks/bridge/sdk/integration/ScheduledActivityRecurringTest.java
> +        assertEquals(3, activities.getItems().size());
Yes this shouldn't have been changed, reverting.

2020-05-06 00:29 UTC, DwayneJengSage requested changes

2020-05-06 00:29 UTC, DwayneJengSage commented on src/test/java/org/sagebionetworks/bridge/sdk/integration/ScheduledActivityRecurringTest.java
> +        //assertEquals(ytz4, activities.getItems().get(3).getScheduledOn().toString());
We should also restore this last assert and the comments as well.

2020-05-06 16:33 UTC, alxdarksage commented on src/test/java/org/sagebionetworks/bridge/sdk/integration/ScheduledActivityRecurringTest.java
> +        //assertEquals(ytz4, activities.getItems().get(3).getScheduledOn().toString());
I've reverted these changes, they were unintentional (I think they were there when I created the branch from some prior testing). Thanks for catching this.

2020-05-06 20:28 UTC, DwayneJengSage approved these changes

2020-05-06 20:33 UTC, merged