Additions to integration tests for recent changes.
Sage-Bionetworks/BridgeIntegrationTests pull request #432
Opened 2020-05-20 20:07 UTC by alxdarksage

2020-05-20 23:58 UTC, DwayneJengSage requested changes

2020-05-20 23:58 UTC, DwayneJengSage commented on src/test/java/org/sagebionetworks/bridge/sdk/integration/CRCTest.java
> +        HealthDataRecordList records = user.getClient(InternalApi.class)
This uses a global secondary index. Consider adding a 1-2 second sleep.

Note that we have been having a lot of Global Secondary Index failures lately. See https://sagebionetworks.jira.com/browse/BRIDGE-2828  (which I think would be a good task for an intern.)

2020-05-20 23:58 UTC, DwayneJengSage commented on src/test/java/org/sagebionetworks/bridge/sdk/integration/CRCTest.java
> +                .getHealthDataByCreatedOn(DateTime.now().minusMinutes(10), DateTime.now().plusMinutes(10))
Also, clock skew on Jenkins has been known to exceed more than 10 minutes. I recommend setting this to plus/minus an hour. (If clock skew gets that high, we probably have other concerns.)

2020-05-21 19:56 UTC, alxdarksage commented on src/test/java/org/sagebionetworks/bridge/sdk/integration/CRCTest.java
> +        HealthDataRecordList records = user.getClient(InternalApi.class)
Added

2020-05-21 21:04 UTC, DwayneJengSage requested changes

2020-05-21 21:04 UTC, DwayneJengSage commented on src/test/java/org/sagebionetworks/bridge/sdk/integration/CRCTest.java
> +                .getHealthDataByCreatedOn(DateTime.now().minusMinutes(10), DateTime.now().plusMinutes(10))
Should also change the time range here.

2020-05-21 21:04 UTC, DwayneJengSage commented on src/test/java/org/sagebionetworks/bridge/sdk/integration/CRCTest.java
> +                .getHealthDataByCreatedOn(DateTime.now().minusMinutes(10), DateTime.now().plusMinutes(10))
Should also change the time range here.

2020-05-22 10:15 UTC, DwayneJengSage approved these changes

2020-05-22 16:53 UTC, merged