Organizations
Sage-Bionetworks/BridgeIntegrationTests pull request #440
Opened 2020-06-17 00:29 UTC by alxdarksage

2020-06-17 22:44 UTC, DwayneJengSage requested changes

2020-06-17 22:44 UTC, DwayneJengSage commented on src/test/java/org/sagebionetworks/bridge/sdk/integration/OrganizationTest.java
> +            orgApi.getOrganization(orgId).execute().body();
Add a test for getOrganization() that finds the org.

2020-06-18 18:00 UTC, alxdarksage commented on src/test/java/org/sagebionetworks/bridge/sdk/integration/OrganizationTest.java
> +            orgApi.getOrganization(orgId).execute().body();
Added

2020-06-18 22:36 UTC, DwayneJengSage approved these changes

2020-06-19 00:03 UTC, merged