Integration Tests for Participant File Service
Sage-Bionetworks/BridgeIntegrationTests pull request #466
Opened 2020-09-18 05:56 UTC by kss39

2020-09-23 02:29 UTC, DwayneJengSage requested changes

2020-09-23 02:29 UTC, DwayneJengSage commented on src/test/java/org/sagebionetworks/bridge/sdk/integration/ParticipantFileTest.java
> +        }
This is going to infinite loop, because you never update remainder, so it will never be empty.

2020-09-23 02:29 UTC, DwayneJengSage commented on src/test/java/org/sagebionetworks/bridge/sdk/integration/ParticipantFileTest.java
> +        ParticipantFileList results = userApi.getParticipantFiles(null, 5).execute().body();
We should also include a test for getParticipantFile() by file ID.

2020-10-14 05:36 UTC, DwayneJengSage approved these changes

2020-11-30 21:00 UTC, alxdarksage approved these changes

2020-11-30 21:00 UTC, alxdarksage commented on pom.xml
> +            <version>0.21.7</version>
Be sure to update to the final SDK version for your changes.

2020-12-04 20:09 UTC, merged