Org administrator API tests
Sage-Bionetworks/BridgeIntegrationTests pull request #488
Opened 2020-11-30 18:32 UTC by alxdarksage

New APIs to create and manage administrative accounts, as a separate task from participants in studies.

2020-12-02 04:13 UTC, DwayneJengSage requested changes

2020-12-02 04:13 UTC, DwayneJengSage commented on src/test/java/org/sagebionetworks/bridge/sdk/integration/AccountsTest.java
> +        assertEquals(PHONE.getNumber(), info.getPhone().getNumber()); // unchanged
The old version of the test used a different phone number. The new version of the test updates the phone number to itself, so we don't actually test anything interesting here.

2020-12-02 21:56 UTC, alxdarksage commented on src/test/java/org/sagebionetworks/bridge/sdk/integration/AccountsTest.java
> +        assertEquals(PHONE.getNumber(), info.getPhone().getNumber()); // unchanged
Changed to add a different phone number before trying again (also doesn't change the credential).

2020-12-03 21:48 UTC, DwayneJengSage approved these changes

2020-12-04 00:28 UTC, merged