Study coordinator
Sage-Bionetworks/BridgeIntegrationTests pull request #493
Opened 2020-12-18 03:26 UTC by alxdarksage

2021-01-14 07:10 UTC, DwayneJengSage requested changes
Add tests for following APIs?
* deleteTestParticipant
* getEnrollmentsForUser

2021-01-14 07:10 UTC, DwayneJengSage commented on src/test/java/org/sagebionetworks/bridge/sdk/integration/ForStudyCoordinatorsTest.java
> +        TestUser researcher = TestUserHelper.createAndSignInUser(ForStudyCoordinatorsTest.class, false, RESEARCHER);
Cleanup the researcher?

2021-01-14 21:06 UTC, alxdarksage commented on src/test/java/org/sagebionetworks/bridge/sdk/integration/ForStudyCoordinatorsTest.java
> +            coordApi.resendStudyParticipantConsentAgreement(STUDY_ID_1, userId, TEST_APP_ID).execute();
added fail() statements a few places where they were missing. Added tests for deleteTestParticipant and getEnrollmentsForUser. Added consent of user to verify resentStudyParticipantConsentAgreement succeeds.

2021-01-14 21:53 UTC, alxdarksage commented on src/test/java/org/sagebionetworks/bridge/sdk/integration/ForStudyCoordinatorsTest.java
> +            coordApi.sendStudyParticipantNotification(STUDY_ID_1, userId, message).execute();
added here and elsewhere

2021-01-14 21:53 UTC, alxdarksage commented on src/test/java/org/sagebionetworks/bridge/sdk/integration/ForStudyCoordinatorsTest.java
> +            coordApi.getStudyParticipantEnrollments(STUDY_ID_2, userId).execute();
added here and elsewhere

2021-01-14 22:02 UTC, alxdarksage commented on src/test/java/org/sagebionetworks/bridge/sdk/integration/ForStudyCoordinatorsTest.java
> +        TestUser researcher = TestUserHelper.createAndSignInUser(ForStudyCoordinatorsTest.class, false, RESEARCHER);
Re-written to clean up account in @AfterTest

2021-01-19 03:13 UTC, DwayneJengSage approved these changes

2021-01-19 17:49 UTC, merged