Added participant data integration tests.
Sage-Bionetworks/BridgeIntegrationTests pull request #508
Opened 2021-02-09 20:45 UTC by kellyyangsong

Please let me know if I'm on the right track - I'm testing CRUD functionalities for the user and worker as well as the exception being thrown in response to a bad request.

2021-02-10 09:35 UTC, DwayneJengSage requested changes

2021-02-10 09:35 UTC, DwayneJengSage commented on src/test/java/org/sagebionetworks/bridge/sdk/integration/ParticipantDataTest.java
> +        results = workersApi.getAllDataForAdminWorker(appId, userId, offsetKey, pageSize).execute().body();
Also test getDataByIdentifierForAdminWorker()

2021-02-10 09:35 UTC, DwayneJengSage commented on src/test/java/org/sagebionetworks/bridge/sdk/integration/ParticipantDataTest.java
> +        adminsApi.deleteAllParticipantDataForAdmin(user.getAppId(), user.getUserId()).execute();
Also test deleteDataForAdmin()

2021-02-10 09:35 UTC, DwayneJengSage commented on src/test/java/org/sagebionetworks/bridge/sdk/integration/ParticipantDataTest.java
> +        HashSet<String> expectedIdentifiers = new HashSet<>(Arrays.asList(identifier1, identifier2, identifier3));
Minor: You can use ImmutableSet.of(identifier1, identifier2, identifier3) to make this easier to write.

2021-02-10 09:35 UTC, DwayneJengSage commented on src/test/java/org/sagebionetworks/bridge/sdk/integration/ParticipantDataTest.java
> +        assertFalse(actualIdentifiers.retainAll(expectedIdentifiers));
You can use assertEquals() to check that two sets have the same values.

2021-02-10 09:35 UTC, DwayneJengSage commented on src/test/java/org/sagebionetworks/bridge/sdk/integration/ParticipantDataTest.java
> +        userApi.deleteDataByIdentifier(identifier3);
We should verify after this step that the data we deleted now no longer exists.

2021-02-10 09:35 UTC, DwayneJengSage commented on src/test/java/org/sagebionetworks/bridge/sdk/integration/ParticipantDataTest.java
> +        adminsApi.deleteAllParticipantDataForAdmin(user.getAppId(), user.getUserId()).execute();
If the three previous calls to deleteDataByIdentifier() delete all the data, so this call doesn't actually do anything. Try using deleteDataByIdentifier() once and use this call to delete all the rest.

2021-02-10 09:35 UTC, DwayneJengSage commented on src/test/java/org/sagebionetworks/bridge/sdk/integration/ParticipantDataTest.java
> +        HashSet<String> expectedIdentifiers = new HashSet<>(Arrays.asList(identifier1, identifier2, identifier3));
Similarly here.

2021-02-10 09:35 UTC, DwayneJengSage commented on src/test/java/org/sagebionetworks/bridge/sdk/integration/ParticipantDataTest.java
> +        assertFalse(actualIdentifiers.retainAll(expectedIdentifiers));
Similarly here.

2021-02-10 09:35 UTC, DwayneJengSage commented on src/test/java/org/sagebionetworks/bridge/sdk/integration/ParticipantDataTest.java
> +        participantData.setData(String.valueOf(node));
We'll want to change JavaSDK so that setData is an object instead of a String.

I'm not sure of the GSON library works with Jackson ObjectNodes. We might need to use a Map.

2021-02-10 09:35 UTC, DwayneJengSage commented on src/test/java/org/sagebionetworks/bridge/sdk/integration/ParticipantDataTest.java
> +        results = workersApi.getAllDataForAdminWorker(appId, userId, offsetKey, pageSize).execute().body();
Let's also add pagination tests for getAllDataForSelf() and getAllDataForAdminWorker(). Something simple like creating 10 Participant Data and paginating through with page size 5 to make sure we get all 10 results.

2021-02-12 00:22 UTC, kellyyangsong commented on src/test/java/org/sagebionetworks/bridge/sdk/integration/ParticipantDataTest.java
> +        adminsApi.deleteAllParticipantDataForAdmin(user.getAppId(), user.getUserId()).execute();
As I'm figuring this out, I'm realizing that because both of these return a ForwardCursorPagedResourceList<String>, that maybe I need to use something other than StringList because it appears to represent ResourceList<String> rather than a paged one in the swagger docs. I can't get the nextPageOffsetKey or page through results right now. 

![Screen Shot 2021-02-11 at 4 18 22 PM](https://user-images.githubusercontent.com/69649063/107715787-de89fc80-6c84-11eb-94f9-5a091d56ce9d.png)

Should I make a new swagger doc for a ForwardCursorPagedResourceList<String>?

2021-02-12 00:24 UTC, kellyyangsong commented on src/test/java/org/sagebionetworks/bridge/sdk/integration/ParticipantDataTest.java
> +        adminsApi.deleteAllParticipantDataForAdmin(user.getAppId(), user.getUserId()).execute();
I just found paged_string.yml! This should do it.

2021-02-12 23:53 UTC, DwayneJengSage requested changes

2021-02-12 23:53 UTC, DwayneJengSage commented on src/test/java/org/sagebionetworks/bridge/sdk/integration/ParticipantDataTest.java
> +        assertFalse(actualIdentifiers.retainAll(expectedIdentifiers));
Missed one: This one can also be assertEquals()

2021-02-12 23:53 UTC, DwayneJengSage commented on src/test/java/org/sagebionetworks/bridge/sdk/integration/ParticipantDataTest.java
> +        for (; i < 5; i++) {
This means that when i = 5, this loop does nothing. I think what you mean is the input should be start, and the for loop should be i < start + 5.

2021-02-13 00:03 UTC, kellyyangsong commented on src/test/java/org/sagebionetworks/bridge/sdk/integration/ParticipantDataTest.java
> +        for (; i < 5; i++) {
wow such a good catch

2021-02-13 00:36 UTC, DwayneJengSage approved these changes

2021-02-23 00:04 UTC, alxdarksage approved these changes

2021-02-23 00:18 UTC, merged