User note access
Sage-Bionetworks/BridgeIntegrationTests pull request #541
Opened 2021-06-09 17:07 UTC by jnelsonjava

- Verifying only Admins can view/update notes.
- Notes do not set during Account/Participant creation.

2021-06-09 22:36 UTC, DwayneJengSage requested changes

2021-06-09 22:36 UTC, DwayneJengSage commented on src/test/java/org/sagebionetworks/bridge/sdk/integration/AccountsTest.java
> +        String testUserId = admin.getClient(ForAdminsApi.class).createUser(signUp).execute().body().getId();
We should use emailUserId so that our After method automatically cleans the account for us. Otherwise, if this test fails, the deleteAccount() at the end of the function doesn't get called, and the test account stays in the database.

2021-06-09 22:36 UTC, DwayneJengSage commented on src/test/java/org/sagebionetworks/bridge/sdk/integration/AccountsTest.java
> +        String testUserId = admin.getClient(ForAdminsApi.class).createUser(signUp).execute().body().getId();
Similarly here.

2021-06-09 22:36 UTC, DwayneJengSage commented on src/test/java/org/sagebionetworks/bridge/sdk/integration/AccountsTest.java
> +    private TestUser consentedUser;
Is this being used?

2021-06-09 22:49 UTC, jnelsonjava commented on src/test/java/org/sagebionetworks/bridge/sdk/integration/AccountsTest.java
> +        // Verifying the note exists on test user's account
This is tested in crudAccount()

2021-06-09 22:54 UTC, jnelsonjava commented on src/test/java/org/sagebionetworks/bridge/sdk/integration/UserParticipantTest.java
> +        TestUser admin = TestUserHelper.createAndSignInUser(UserParticipantTest.class, true, Role.ADMIN);
Set to Researcher instead of Admin

2021-06-09 22:57 UTC, jnelsonjava commented on src/test/java/org/sagebionetworks/bridge/sdk/integration/UserParticipantTest.java
> +        } finally {
User the "Before" and "After" sections to set up and delete accounts instead of a try/finally.

2021-06-10 21:59 UTC, jnelsonjava commented on src/test/java/org/sagebionetworks/bridge/sdk/integration/AccountsTest.java
> +    private TestUser consentedUser;
It's not being used. Removed it in the next commit.

2021-06-10 22:00 UTC, jnelsonjava commented on src/test/java/org/sagebionetworks/bridge/sdk/integration/AccountsTest.java
> +        String testUserId = admin.getClient(ForAdminsApi.class).createUser(signUp).execute().body().getId();
Makes sense! It's switched over now.

2021-06-10 22:03 UTC, jnelsonjava commented on src/test/java/org/sagebionetworks/bridge/sdk/integration/AccountsTest.java
> +        String testUserId = admin.getClient(ForAdminsApi.class).createUser(signUp).execute().body().getId();
This is updated now as well.

2021-06-10 22:06 UTC, jnelsonjava commented on src/test/java/org/sagebionetworks/bridge/sdk/integration/UserParticipantTest.java
> +    public void nonAdminCanNotUpdateOrViewRecordNote() throws Exception {
Collapsed three tests into this one to check non-Admin interaction with the note field.

2021-06-11 01:29 UTC, DwayneJengSage approved these changes

2021-06-11 15:59 UTC, alxdarksage approved these changes

2021-06-11 17:44 UTC, merged