Verifying previous S3 file is deleted on create request
Sage-Bionetworks/BridgeIntegrationTests pull request #547
Opened 2021-06-24 22:16 UTC by jnelsonjava

2021-06-25 00:16 UTC, DwayneJengSage requested changes

2021-06-25 00:16 UTC, DwayneJengSage commented on src/test/java/org/sagebionetworks/bridge/sdk/integration/ParticipantFileTest.java
> +            assertEquals("Not Found", exception.getMessage());
What kind of exception gets thrown here? Ideally it should be an EntityNotFoundException, or at least a BridgeSDKException with status code 404.

2021-06-25 00:57 UTC, jnelsonjava commented on src/test/java/org/sagebionetworks/bridge/sdk/integration/ParticipantFileTest.java
> +            assertEquals("Not Found", exception.getMessage());
It is a BridgeSDKException on this one. The GET route throws an EntityNotFoundException if the ParticipantFile record is missing, but it seems to throw a BridgeSDKException on the redirect. Would it be better to assert the type of exception?

2021-06-25 00:59 UTC, DwayneJengSage commented on src/test/java/org/sagebionetworks/bridge/sdk/integration/ParticipantFileTest.java
> +            assertEquals("Not Found", exception.getMessage());
Hmm, I think the cleanest thing to do is in BridgeServer, catch the Amazon exception, check if it's a Not Found, and then re-throw it as a Bridge EntityNotFoundException. This would make our JavaSDK throw an EntityNotFoundException, which would make it cleaner.

2021-06-25 15:57 UTC, alxdarksage commented on src/test/java/org/sagebionetworks/bridge/sdk/integration/ParticipantFileTest.java
> +            assertEquals("Not Found", exception.getMessage());
I think the issue is that the method returns a 302 and you only get the 404 when the HTTP client redirects to S3. So this is a translation of an S3 return status. I would at least catch BridgeSDKException to verify we're catching this, and it should wrap the underlying exception, whatever it is (probably an OkHttp client exception)? We can verify that.

2021-06-25 15:57 UTC, alxdarksage requested changes
See comment

2021-06-25 18:55 UTC, DwayneJengSage commented on src/test/java/org/sagebionetworks/bridge/sdk/integration/ParticipantFileTest.java
> +            assertEquals("Not Found", exception.getMessage());
Excellent point. I guess we should figure out the exact mechanism of the exception being thrown here. I assumed that our call to S3.generatePresignedUrl() was throwing within BridgeServer. But if S3 is just generating a link that points to nothing, then it would be the redirect that's throwing, and we wouldn't be able to intercept that and replace it with a Bridge EntityNotFoundException. In this case, it would be some kind of HTTP Exception with status 404. Might be worthwhile stepping through this in a debugger and seeing what's happening.

Other open questions: Does the HTTP tool we use in Integ Tests automatically follow redirects? I know that Postman has a toggle for follow redirects.

2021-06-28 22:57 UTC, alxdarksage requested changes
One minor change (I think you are still looking at what the underlying exception is that we're receiving back when the file doesn't exist on S3?)

2021-06-28 22:57 UTC, alxdarksage commented on src/test/java/org/sagebionetworks/bridge/sdk/integration/ParticipantFileTest.java
> +        }
This second catch is unnecessary. If the exception is not BridgeSDKException, it will be thrown out of the method, causing the test to fail.

2021-06-28 23:35 UTC, alxdarksage approved these changes

2021-06-30 23:22 UTC, DwayneJengSage approved these changes

2021-07-01 17:46 UTC, merged