Test changes
Sage-Bionetworks/BridgeIntegrationTests pull request #571
Opened 2021-09-10 18:58 UTC by alxdarksage

BRIDGE-3053

Developers must now operate on accounts that are marked as test accounts. For some calls, this wasn't previously necessary.

2021-09-13 22:22 UTC, alxdarksage commented on src/test/java/org/sagebionetworks/bridge/sdk/integration/ParticipantsTest.java
>          SchedulesV1Api schedulePlanApi = user.getClient(SchedulesV1Api.class);
Let's add an integration test of the permissions structure itself, not just as a side effect of set up for other tests. 

Also here, we should have really split out the developer and the test account being operated on. But check why developer couldn't operate on self.

2021-09-13 22:24 UTC, alxdarksage commented on src/test/java/org/sagebionetworks/bridge/sdk/integration/ReportTest.java
> +                .isTestUser().createAndSignInUser();
Rename to "asTestUser"

2021-09-13 22:25 UTC, alxdarksage commented on src/test/java/org/sagebionetworks/bridge/sdk/integration/ReportTest.java
> +                .isTestUser().createAndSignInUser();
If this is a worker, then the account does not need to be a test account.

2021-09-13 22:25 UTC, alxdarksage commented on src/test/java/org/sagebionetworks/bridge/sdk/integration/ReportTest.java
> +                .isTestUser().createAndSignInUser();
Again, worker.

2021-09-13 22:26 UTC, alxdarksage commented on src/test/java/org/sagebionetworks/bridge/sdk/integration/ReportTest.java
> +                .isTestUser().createAndSignInUser();
Same. This test needs to succeed for a production account too.

2021-09-13 22:53 UTC, alxdarksage commented on src/test/java/org/sagebionetworks/bridge/sdk/integration/ReportTest.java
> +                .isTestUser().createAndSignInUser();
It was marked as a test account because a developer account was used to delete the associated reports. For this reason, I've removed the test_user flag here, and used an admin to do test cleanup.

2021-09-13 23:07 UTC, alxdarksage commented on src/test/java/org/sagebionetworks/bridge/sdk/integration/ReportTest.java
> +                .isTestUser().createAndSignInUser();
Changing cleanup removes the need to make a test account.

2021-09-13 23:08 UTC, alxdarksage commented on src/test/java/org/sagebionetworks/bridge/sdk/integration/ReportTest.java
> +                .isTestUser().createAndSignInUser();
Removed after fixing cleanup.

2021-09-14 16:19 UTC, alxdarksage commented on src/test/java/org/sagebionetworks/bridge/sdk/integration/ReportTest.java
> +                .isTestUser().createAndSignInUser();
renamed to "withTestDataGroup()"

2021-09-14 16:28 UTC, alxdarksage commented
In addition to verifying these changes were for cleanup, and switching to the user of an admin account so we don't have to add "test_user" to accounts at random, I also added a test to more systematically verify security for getting an individual account and for searching.

2021-09-23 23:53 UTC, DwayneJengSage requested changes

2021-09-23 23:53 UTC, DwayneJengSage commented on src/test/java/org/sagebionetworks/bridge/sdk/integration/AuthorizationTest.java
> +        resPartApi.updateParticipant(testUserId, testParticipant);
These are missing .execute(). Recommend double-checking to make sure all the calls have their .execute().

2021-09-24 23:05 UTC, alxdarksage commented on src/test/java/org/sagebionetworks/bridge/sdk/integration/AuthorizationTest.java
> +        resPartApi.updateParticipant(testUserId, testParticipant);
Added and checked other methods for .execute().

2021-09-28 00:25 UTC, DwayneJengSage approved these changes

2021-09-29 00:01 UTC, merged