Enrollment note field
Sage-Bionetworks/BridgeIntegrationTests pull request #590
Opened 2021-10-18 21:21 UTC by jnelsonjava

Bridge-3095

- Adding tests for enrollment notes on create and update

2021-10-18 22:54 UTC, jnelsonjava commented on src/test/java/org/sagebionetworks/bridge/sdk/integration/EnrollmentTest.java
> +import org.sagebionetworks.bridge.rest.model.EnrollmentDetail;
Not used

2021-10-18 22:54 UTC, jnelsonjava commented on src/test/java/org/sagebionetworks/bridge/sdk/integration/EnrollmentTest.java
> +        // TODO: does the admin need to be signed out/deleted?
Do not delete the admin.

2021-10-18 22:56 UTC, jnelsonjava commented on src/test/java/org/sagebionetworks/bridge/sdk/integration/EnrollmentTest.java
> +            enrollment.setNote("initial test enrollment note should not set");
Should actually work.

2021-10-18 22:59 UTC, jnelsonjava commented on src/test/java/org/sagebionetworks/bridge/sdk/integration/EnrollmentTest.java
Not needed.

2021-10-26 20:10 UTC, alxdarksage requested changes

2021-10-27 17:26 UTC, alxdarksage approved these changes

2021-10-27 20:10 UTC, merged