Add integration test for participant file download rate limiting
Sage-Bionetworks/BridgeIntegrationTests pull request #687
Opened 2022-07-05 23:43 UTC by imranmaj

[https://sagebionetworks.jira.com/browse/BRIDGE-2941](https://sagebionetworks.jira.com/browse/BRIDGE-2941)

2022-07-06 22:16 UTC, jnelsonjava approved these changes
Approved. But one minor addition. Since the SDK version is bumping, also bump the bridge rest-client in the integration test's pom.xml to match.

2022-07-06 23:58 UTC, jnelsonjava commented on pom.xml
> +    <version>0.9.1</version>
Not this version, the one on line 62. Should be 0.25.8 to match the SDK update.

2022-07-07 16:17 UTC, imranmaj commented on pom.xml
> +    <version>0.9.1</version>
Ah I see, the dependency

2022-07-14 05:08 UTC, DwayneJengSage requested changes
Overall looks good. A few minor optimizations.

2022-07-14 05:08 UTC, DwayneJengSage commented on src/test/java/org/sagebionetworks/bridge/sdk/integration/ParticipantFileTest.java
> +        Thread.sleep(5000);
Don't need to sleep, since Before is run for each test method, so each test will have its own user.

This is important because the tests already take a very long time, so we don't want to add unnecessary wait time.

2022-07-14 05:08 UTC, DwayneJengSage commented on src/test/java/org/sagebionetworks/bridge/sdk/integration/ParticipantFileTest.java
> +        out.write(StringUtils.repeat("A", 100)); // 100 B in ASCII
Consider instead writing a 1kb file and reading it twice instead of writing 100b file and reading it 11 times. This means there's less overhead setting up the download.

2022-07-14 16:21 UTC, imranmaj commented on src/test/java/org/sagebionetworks/bridge/sdk/integration/ParticipantFileTest.java
> +        Thread.sleep(5000);
The issue I was having is with After, which calls getParticipantFiles in order to clean up the uploaded files immediately a rate limiting violation happens in the test, so that call is also rejected due to rate limiting

2022-07-14 22:14 UTC, DwayneJengSage approved these changes

2022-07-15 23:57 UTC, merged