Add integration tests for demographics
Sage-Bionetworks/BridgeIntegrationTests pull request #691
Opened 2022-08-16 19:56 UTC by imranmaj

[https://sagebionetworks.jira.com/browse/BRIDGE-2964](https://sagebionetworks.jira.com/browse/BRIDGE-2964)

2022-08-23 00:23 UTC, DwayneJengSage requested changes

2022-08-24 23:53 UTC, imranmaj commented on src/test/java/org/sagebionetworks/bridge/sdk/integration/DemographicsTest.java
> +            researchersApi.deleteDemographicUser(TEST_STUDY_ID, consentedUserNotInStudy.getUserId()).execute();
Yes it's supposed to down below, thanks

2022-08-26 01:51 UTC, DwayneJengSage approved these changes

2022-09-08 10:15 UTC, DwayneJengSage approved these changes

2022-09-08 10:29 UTC, DwayneJengSage commented
Note: Server2 build failed. See https://github.com/Sage-Bionetworks/BridgeServer2/pull/618

2022-09-09 18:49 UTC, merged