Integration tests for exportTimelineForStudy API
Sage-Bionetworks/BridgeIntegrationTests pull request #719
Opened 2023-08-02 03:58 UTC by chuguoxipo

2023-08-04 12:05 UTC, DwayneJengSage requested changes

2023-08-04 12:05 UTC, DwayneJengSage commented on src/test/java/org/sagebionetworks/bridge/sdk/integration/Exporter3Test.java
> +            //TestUser admin = TestUserHelper.getSignedInAdmin();
Minor: Remove commented code.

2023-08-29 23:08 UTC, chuguoxipo commented on src/test/java/org/sagebionetworks/bridge/sdk/integration/Exporter3Test.java
> +        studyDesigner = TestUserHelper.createAndSignInUser(StudyBurstTest.class, false, STUDY_DESIGNER);
studyDesigner was set up in beforeClass(). Should we add this in afterClass()?

2023-08-29 23:27 UTC, chuguoxipo commented on src/test/java/org/sagebionetworks/bridge/sdk/integration/Exporter3Test.java
> +        }
Since we also call initForStudy() in exportTimelineForStudy(). This cleans up after one of the test before running the other.

2023-08-31 05:56 UTC, DwayneJengSage commented on src/test/java/org/sagebionetworks/bridge/sdk/integration/Exporter3Test.java
> +        studyDesigner = TestUserHelper.createAndSignInUser(StudyBurstTest.class, false, STUDY_DESIGNER);
Yes, this should be in afterClass()

2023-08-31 05:59 UTC, DwayneJengSage commented on src/test/java/org/sagebionetworks/bridge/sdk/integration/Exporter3Test.java
> +        }
Okay, that makes sense. Thanks!

2023-09-12 07:43 UTC, DwayneJengSage approved these changes

2023-09-18 17:51 UTC, merged